name: simulations

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        py-ver: [3.7, 3.8, 3.9]
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-ver }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - run: tox -e py`echo ${{ matrix.py-ver }} | sed 's#\.##g'`

  fomu:
    runs-on: ubuntu-latest
    container: hdlc/impl
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt update -qq
        apt install -y git python3-pip dfu-util
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        PYTHONPATH=$(pwd) LUNA_PLATFORM=luna.gateware.platform.fomu:FomuPVT python3 examples/usb/acm_serial.py -o fomu.bit
